### ISSUE TITLE
How to extract addresses/address from multisig-scriptPubKey.

### ISSUE THREAD

**Issue by dbdeadka** [Bit-Wasp/bitcoin-php#479]
Really great lib! Thank you very much for it!

I have some question (It seems as bug, but I am not sure, provide some comment please):

I need to extract addresses/address from multisig-scriptPubKey
For example, scriptPubKey = 
5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae
(this scriptPubKey is from btc-transaction with hash 0000a524025cca89db9743a6ec940d2a987bbb7f19f392adb3912b85c7a9a12f )
or scriptPubKey = 
512102fa6ddd34c184151a1868f5233bb77e5efd9b5aa88885825c3c84cc8863fe0b69211c434e54525052545900000000000000000004ebdf000000389f40e9800000000052ae
(this scriptPubKey is from btc-transaction with hash 0000fa31b80b4da025c65c32f06881e321d8eefcd949e0e96deb6e43b9bfc219 )

Next code:
`
<?php

require __DIR__ . "/vendor/autoload.php";

$script = \BitWasp\Bitcoin\Script\ScriptFactory::fromHex("5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae");

$address = \BitWasp\Bitcoin\Address\AddressFactory::getAssociatedAddress($script);

?>
`
Raised RuntimeException: Script type is not associated with an address

I tried to use 
`
$solutions = null;

$type = (new OutputClassifier())->classify($script,$solutions);
`
instead
`
$address = \BitWasp\Bitcoin\Address\AddressFactory::getAssociatedAddress($script);
`
but $type had value "nonstandard" and $solutions variable had null value after executing of this code.

Meanwhile we can see output of bitcoin-daemon

bitcoind@machinename:/home/username$ bitcoin-cli decodescript 5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae 
{
  "asm": "1 046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba25 204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc 2 OP_CHECKMULTISIG",
  "reqSigs": 1,
  "type": "multisig",
  "addresses": ["18888888PPJ8oGeqR6AKmoiKUme9da48Xf"],
  "p2sh": "3Ev41axPPvCjsbzrQMVzhCNimiJxViRyo9"
}        

So this output has destination address = 18888888PPJ8oGeqR6AKmoiKUme9da48Xf.

How could I extract this address using your library?

Additionly I have to note that if I'll try to extract addresses from the output with the multisig scriptPubKey 
(with several destination addresses) - then glory and victory:

`
$script = \BitWasp\Bitcoin\Script\ScriptFactory::fromHex("514104f71366b5cbfb2f87227658cfde6294f02ebb3babcdbc1723f35ed846489e7b5a8565e891096a0f2583160cb19b4ed17d0853fc99cf7412c6041e5b2117e78f2921022d7f68ac457d834fb67a112f3571da0eb6365d4c0523f9f74b298096160a02f752ae");

$solutions = null;

$type = (new OutputClassifier())->classify($script,$solutions);
//$type = multisig

$a1 = PublicKeyFactory::fromHex($solutions[0])->getAddress()->getAddress();
//$a1 = "1MaStErt4XsYHPwfrN9TpgdURLhHTdMenH"

$a2 = PublicKeyFactory::fromHex($solutions[1])->getAddress()->getAddress();
//$a2 = "1MeMwGjff7uG9hHKAE1jJFeGRdfMxNkovX"

`
bitcoind@machinename:/home/username$ bitcoin-cli decodescript 514104f71366b5cbfb2f87227658cfde6294f02ebb3babcdbc1723f35ed846489e7b5a8565e891096a0f2583160cb19b4ed17d0853fc99cf7412c6041e5b2117e78f2921022d7f68ac457d834fb67a112f3571da0eb6365d4c0523f9f74b298096160a02f752ae
{
  "asm": "1 04f71366b5cbfb2f87227658cfde6294f02ebb3babcdbc1723f35ed846489e7b5a8565e891096a0f2583160cb19b4ed17d0853fc99cf7412c6041e5b2117e78f29 022d7f68ac457d834fb67a112f3571da0eb6365d4c0523f9f74b298096160a02f7 2 OP_CHECKMULTISIG",
  "reqSigs": 1,
  "type": "multisig",
  "addresses": ["1MaStErt4XsYHPwfrN9TpgdURLhHTdMenH","1MeMwGjff7uG9hHKAE1jJFeGRdfMxNkovX"],
  "p2sh": "3HtwSa6Dnwnbcfaejc8nu7JsoHuWTZUBrr"
}

Results (at least in context of destination addresses are equal).

**Comment by afk11** [comment]
Yea that makes sense - multisig scripts don't have addresses unless they're pay to script hash. 

To get the same output, do this:
```php

$scripthex = '514104f71366b5cbfb2f87227658cfde6294f02ebb3babcdbc1723f35ed846489e7b5a8565e891096a0f2583160cb19b4ed17d0853fc99cf7412c6041e5b2117e78f2921022d7f68ac457d834fb67a112f3571da0eb6365d4c0523f9f74b298096160a02f752ae';

$script = new \BitWasp\Bitcoin\Script\Script(\BitWasp\Buffertools\Buffer::hex($scripthex));
$classifier = new \BitWasp\Bitcoin\Script\Classifier\OutputClassifier();
if ($classifier->isMultisig($script)) {
    $multisigInfo = new \BitWasp\Bitcoin\Script\ScriptInfo\Multisig($script);
    $pubKeys = $multisigInfo->getKeys();
    print_r($pubKeys);
}
```

The P2SH address isn't relevant because you're talking about bare multisig scripts..

**Comment by dbdeadka** [comment]
**afk11**, thank you for feedback.

Your code is working, but if $scripthex will have another value, "my" value

5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae

then 
$classifier->isMultisig($script) 
code instruction return false and it is not possible to create 
\BitWasp\Bitcoin\Script\ScriptInfo\Multisig
object.

Meanwhile I have to notice that it's multisig, have a look here please:

bitcoind@machinename:/home/username$ bitcoin-cli decodescript 5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae
{
"asm": "1 046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba25 204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc 2 OP_CHECKMULTISIG",
"reqSigs": 1,
"type": "**multisig**",
"addresses": ["18888888PPJ8oGeqR6AKmoiKUme9da48Xf"],
"p2sh": "3Ev41axPPvCjsbzrQMVzhCNimiJxViRyo9"
}

Navigate please, how could I extract address 18888888PPJ8oGeqR6AKmoiKUme9da48Xf
from this the following scriptPubKey hex?

**Comment by afk11** [comment]
```php
if ($classifier->isMultisig($script)) {
    $multisigInfo = new \BitWasp\Bitcoin\Script\ScriptInfo\Multisig($script);
    $pubKeys = $multisigInfo->getKeys();
    foreach ($pubkeys as $pubkey) {
      echo $pubkey->getAddress()->getAddress() . PHP_EOL;
    }
}
```

**Comment by dbdeadka** [comment]
afk11, thank you for feedback.

Try please to execute next snippet of code with  hex of scriptPubKey =

5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae

```
$scripthex = '5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae';

$script = new \BitWasp\Bitcoin\Script\Script(\BitWasp\Buffertools\Buffer::hex($scripthex));

$isMultisig = $classifier->isMultisig($script)`
```

And you'll see that $isMultisig will have value = false, not true.
And it'll impossible to create \BitWasp\Bitcoin\Script\ScriptInfo\Multisig object and extract the addresses.

Meanwhile bitcoind "mean" that it's a multisig hex, how I wrote upper 

bitcoind@machinename:/home/username$ bitcoin-cli decodescript 5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba2521204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc52ae
{
"asm": "1 046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba25 204348414e4345434f00000028000000000bebc200404b8000000000003ffccccc 2 OP_CHECKMULTISIG",
"reqSigs": 1,
"type": "multisig",
"addresses": ["18888888PPJ8oGeqR6AKmoiKUme9da48Xf"],
"p2sh": "3Ev41axPPvCjsbzrQMVzhCNimiJxViRyo9"
} 

What is the problem? Is this scriptPubKey really not multisig? But bitcoind tells that..

**Comment by afk11** [comment]
Yeah ok - it looks like bitcoind is trying to make it work.. 
https://github.com/bitcoin/bitcoin/blob/9692be4a9a9b0e2959cf0352b83a1898f4a7675e/src/rpc/rawtransaction.cpp
https://github.com/bitcoin/bitcoin/blob/8152d3fe57a991e9088d0b9d261d2b10936f45a9/src/script/standard.cpp#L228

It realizes the second public key is invalid, so doesn't add the address. Sort of similar with the classifier, it doesn't accept it because a public key is invalid. 
https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Classifier/OutputClassifier.php#L240

I notice that scriptPubKey is still unspent by the way, it probably never will!

**Comment by afk11** [comment]
Seems solved, closing due to inactivity

**Comment by dbdeadka** [comment]
Excuse me, I was not online last weeks. Thank you for the answer, situation is more understandable.
It seems to me that in last case it's better to return that addresses, which it is possible to extract from scriptpubkey (like in https://github.com/bitcoin/bitcoin/blob/8152d3fe57a991e9088d0b9d261d2b10936f45a9/src/script/standard.cpp#L228
 ), but, certainly it's IMHO only.

But story is not finished yet :(. Try please to execute next snippet of code (based on 
https://www.blocktrail.com/BTC/tx/d01a99b5cf7b258d1431822b0fe151772023ca525269369ce6157bf6e32041cb?txoutIdx=3

):

```
<?php

require __DIR__ . "/../vendor/autoload.php";

$hex = "5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba252102b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff92752ae";
$script = new \BitWasp\Bitcoin\Script\Script(\BitWasp\Buffertools\Buffer::hex($hex));
$solutions = null;
$decoded = $script->getScriptParser()->decode();
$classifier = new \BitWasp\Bitcoin\Script\Classifier\OutputClassifier();

$type = $classifier->classify($script,$solutions);
print "type = " . $type . PHP_EOL;
print "size of soultions = " . count($solutions) . PHP_EOL;

$a1 = BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex($solutions[0])->getAddress()->getAddress();
$a2 = BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex($solutions[1])->getAddress()->getAddress();
```

Code fails:

username@machinename:~/bitcoinphp-lib/tests$ php multisig1.php
type = multisig
size of soultions = 2
PHP Fatal error:  Uncaught exception 'LogicException' with message '36126036814164657098511955728052231927830236627713106616318751105840950552302 has no square root modulo 115792089237316195423570985008687907853269984665640564039457584007908834671663' in /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Math/NumberTheory.php:197
Stack trace:
#0 /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Primitives/CurveFp.php(125): Mdanter\Ecc\Math\NumberTheory->squareRootModP(Object(GMP), Object(GMP))
#1 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/PhpEcc/Adapter/EcAdapter.php(331): Mdanter\Ecc\Primitives\CurveFp->recoverYfromX(false, Object(GMP))
#2 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/PhpEcc/Serializer/Key/PublicKeySerializer.php(87): BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Adapter\EcAdapter->publicKeyFromBuffer(Object(BitWasp\Buffertools\Buffer))
#3 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Key/PublicKeyFactory.php(29): BitWasp\Bitcoin\Crypto in /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Math/NumberTheory.php on line 197


My php version:
$ php --version
PHP 5.6.11-1ubuntu3.4 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

In the same time:

bitcoind@machinename:/home/username$ bitcoin-cli decodescript 5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba252102b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff92752ae
{
  "asm": "1 046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba25 02b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff927 2 OP_CHECKMULTISIG",
  "reqSigs": 1,
  "type": "multisig",
  "addresses": [
    "18888888PPJ8oGeqR6AKmoiKUme9da48Xf",
    "1NLj9gQZwTQBgNApxqcA7fM41E8usnUsXg"
  ],
  "p2sh": "3BySBpZgkeirer6SDBhogQYy6LMEG8b3vc"
}

How could you comment this behaviour?
