### ISSUE TITLE
Type error in Buffertools/TypeFactory.php

### ISSUE THREAD

**Issue by AdamSEY** [Bit-Wasp/bitcoin-php#698]
```
2018-05-20 23:51:03 Exception Name: [TypeError], Code: [0] Message:[Argument 1 passed to BitWasp\Buffertools\Types\AbstractSignedInt::__construct() must be an instance of Mdanter\Ecc\Math\GmpMathInterface, integer given, called in /var/www/vendor/bitwasp/buffertools/src/Buffertools/TypeFactory.php on line 203] in ./var/www/vendor/bitwasp/buffertools/src/Buffertools/Types/AbstractSignedInt.php. on line 16  
```

**Trace:** 
```
#0 /var/www/vendor/bitwasp/buffertools/src/Buffertools/TypeFactory.php(203): BitWasp\Buffertools\Types\AbstractSignedInt->__construct(0) 

#1 [internal function]: BitWasp\Buffertools\TypeFactory->int32le() 

#2 /var/www/vendor/bitwasp/buffertools/src/Buffertools/CachingTypeFactory.php(257): call_user_func_array(Array, Array) 

#3  /var/www/vendor/bitwasp/bitcoin/src/Serializer/Types.php(198): BitWasp\Buffertools\CachingTypeFactory->int32le() 

#4 /var/www/vendor/bitwasp/bitcoin/src/Serializer/Transaction/TransactionSerializer.php(51): BitWasp\Bitcoin\Serializer\Types::int32le()

#5 /var/www/vendor/bitwasp/bitcoin/src/Transaction/TransactionFactory.php(48): BitWasp\Bitcoin\Serializer\Transaction\TransactionSerializer->__construct() 

#6 /var/www/vendor/bitwasp/bitcoin/src/Transaction/TransactionFactory.php(39): BitWasp\Bitcoin\Transaction\TransactionFactory::fromBuffer(Object(BitWasp\Buffertools\Buffer))

#7 BitWasp\Bitcoin\Transaction\TransactionFactory::fromHex('010000000198412...')```

**Comment by AdamSEY** [comment]
I had a different Mdanter version which caused the issue.
